'use server'

// for lib
// could expand with gmail and 2fa

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { createToken } from '@/utils/auth-user';
import bcrypt from "bcrypt";


export async function handleRegister(formData: FormData, lang: string = 'en') {
  const password = formData.get("password") as string;

  try {
    // User unicity CHECK
    const existingUser = false // TBD check in DB if user exists //same username valid? or since diff id okay
    if (existingUser) return { error: "User already exists" };

    // Hashing password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    // Storing data
    // TBD Store user data in DB

  } catch (e) {
    return { error: "Registration failed" };
  }
  redirect(`/${lang}/login`);
}

  

export async function handleLogin(formData: FormData, lang: string = 'en') {
    const password = formData.get("password") as string;
    if (!password ) { // TBD also username?
        return { error: "Please fill in all fields" };
    }
    let token; 

    try {
        const user = {password: "1", id: "1"} // TBD extraer user desde BD
        
        if (!user || !(await bcrypt.compare(password, user.password))) {
            return { error: "Invalid ID/username or password" }; //TBD
        }

        token = await createToken(user.id);
        await loginUser(token); // Set cookie

    } catch (error) {
        return { error: "Connection error" };
    }

    redirect(`/${lang}/projects`);
}


// set cookie onto the cookie jar
export async function loginUser(token: string, lang: string = 'en') {
  const cookieStore = await cookies()

  // set token generated by jose.SignJWT()
  cookieStore.set('auth_token', token, {
    httpOnly: true, 
    secure: process.env.NODE_ENV === 'production', // false for development for localhost
    sameSite: 'lax', 
    path: '/',      
    maxAge: 60 * 60 * 24 * 7 // 1 week
  })
}

export async function logout(lang: string = 'en') {
  const cookieStore = await cookies()
  cookieStore.delete('auth_token') // Removes the cookie
  redirect(`/${lang}`) // Redirect to "home" page
}

